language: java

jdk:
  - openjdk16

sudo: false

env:
  global:
    - CODECOV_TOKEN="8af8a01d-bd55-4a42-a6d2-71cb2f7f69da"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - e.g.zakharov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always